# Generated by Django 5.1.7 on 2025-03-25 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Заголовок")),
                ("description", models.TextField(verbose_name="Текст новости")),
                ("author", models.CharField(max_length=40, verbose_name="Автор")),
                ("datetime", models.DateTimeField(verbose_name="Дата и время")),
            ],
            options={
                "verbose_name": "Новость",
                "verbose_name_plural": "Новости",
            },
        ),
    ]
